services:
  emat-app:
    image: emat:latest
    container_name: emat-app

    ports:
      - "127.0.0.1:8086:8086"

    environment:
      SPRING_PROFILES_ACTIVE: "prod"

      VAULT_SCHEME: "https"
      VAULT_HOST: "vault-emat.metaversedu.in"
      VAULT_PORT: "443"

      VAULT_ROLE_ID: "${VAULT_ROLE_ID}"
      VAULT_SECRET_ID: "${VAULT_SECRET_ID}"

    restart: unless-stopped